# configs/inference_config.yaml

# Inference Parameters
inference_params:
  input_dir: "/home/fred/Projetos/DATASETS/VoiceBank-DEMAND-16k/test/noisy/"
  output_dir: "denoised_results_specnet"
  checkpoint_path: "logs/checkpoints/last.ckpt"  # Change to your best checkpoint
  cpu: false

# Model Parameters (required to instantiate the LightningModule)
model_hparams:
  lr: 0.0001
  sample_rate: 16000
  # CleanSpecNet Architecture
  input_channels: 513
  num_conv_layers: 5
  kernel_size: 4
  stride: 1
  hidden_dim: 512
  num_attention_layers: 5
  num_heads: 8
  dropout: 0.1

# Audio parameters for preprocessing
audio_params:
  target_sample_rate: 16000
  n_fft: 1024
  hop_length: 256
